[theme]
primaryColor = "#4cd4d2"
backgroundColor = "#fffefeff"
secondaryBackgroundColor = "#03a8aeff"
textColor = "##b0b0bff"
font = "sans serif"

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
