[theme]
primaryColor = "#01014a"
backgroundColor = "#01014a"
secondaryBackgroundColor = "#028684ff"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = true
showWarningOnDirectExecution = true

[logger]
level = "warning"

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
